[versions]
roomRuntime = "2.8.3"
lifecycleRuntimeKtx = "2.9.4"
runtimeLivedata = "1.9.4"
ksp = "2.1.10-1.0.31"
[libraries]
androidx-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata", version.ref = "runtimeLivedata" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomRuntime" }
androidx-room-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
[plugins]
devtoolsKsp = { id = "com.google.devtools.ksp", version.ref = "ksp"}